SELECT * FROM emp_copy WHERE EMPLOYEE_ID = 100;
DELETE FROM emp_copy WHERE EMPLOYEE_ID = 100;
SELECT * FROM emp_copy WHERE EMPLOYEE_ID = 100;
ROLLBACK;
SELECT * FROM emp_copy WHERE EMPLOYEE_ID = 100;

SELECT * FROM emp_copy WHERE EMPLOYEE_ID = 101;
DELETE FROM emp_copy WHERE EMPLOYEE_ID = 101;
SELECT * FROM emp_copy WHERE EMPLOYEE_ID = 101;
ROLLBACK;
SELECT * FROM emp_copy WHERE EMPLOYEE_ID = 101;

COMMIT;
SELECT * FROM account_tbl;

SHOW DATABASES;
SHOW USER;
CREATE USER jdbc IDENTIFIED BY 'jdbc';
DROP USER jdbc;
CREATE DATABASE memberdb;
DROP DATABASE memberdb;
GRANT ALL privileges ON memberdb.* TO jdbc@'%';

select host,user from mysql.user; -- DB 계정 목록 보는 방법

SHOW GRANTS FOR 'jdbc'@'%';








